### PR TITLE
PREAPPS-500: Removing buttons from search header and adding new button to form.

### PR DESCRIPTION
**Pull request by dlesynacor**

### CODE REVIEW

**Comment by billneff79** [comment]
@dlesynacor According to the acceptance criteria of the ticket, hitting enter and clicking the search icon are supposed to be NoOps in verticals other than the Mail vertical.  In the current code, they take you to the search page.

**Comment by billneff79** [comment]
@tstegner I'm fine with that as long as you update the acceptance criteria on the ticket

**Comment by billneff79** [comment]
oops - meant to comment, not Close and Comment

**Comment by tstegner** [comment]
@billneff79 Can you push this?

**Pull request merged**
